### ISSUE TITLE
SSL error upon connection

### ISSUE THREAD

**Issue by bleykauf** [hermitdemschoenenleben/linien#252]
GUI error simply states "Exception occurred when connecting to the device".

Login via PowerShell works. Note: Just created a new key pair. Before, things worked fine.

```
server is not running. Launching it!
Traceback (most recent call last):
  File ".\linien\client\connection.py", line 203, in _connect
    call_on_error=call_on_error,
  File ".\linien\client\connection.py", line 106, in _connect_rpyc
    server, port, service=self.client_service, config={"allow_pickle": True}
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\rpyc\utils\factory.py", line 98, in connect
    s = SocketStream.connect(host, port, ipv6=ipv6, keepalive=keepalive)
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\rpyc\core\stream.py", line 172, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\rpyc\core\stream.py", line 124, in _connect
    s = socket_backoff_connect(family, socktype, proto, sockaddr, timeout, attempts)
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\rpyc\lib\__init__.py", line 131, in socket_backoff_connect
    sock.connect(addr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\linien\gui\ui\device_manager.py", line 325, in run
    on_connection_lost=self.on_connection_lost,
  File ".\linien\client\connection.py", line 183, in __init__
    call_on_error=on_connection_lost,
  File ".\linien\client\connection.py", line 77, in __init__
    call_on_error=call_on_error,
  File ".\linien\client\connection.py", line 220, in _connect
    run_server(host, user, password, port)
  File ".\linien\client\utils.py", line 24, in run_server
    ssh = connect_ssh(host, user, password)
  File ".\linien\client\utils.py", line 19, in connect_ssh
    ssh.connect(hostname=host, username=user, password=password)
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\paramiko\client.py", line 446, in connect
    passphrase,
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\paramiko\client.py", line 735, in _auth
    filename, pkey_class, passphrase
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\paramiko\client.py", line 586, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\paramiko\pkey.py", line 235, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\paramiko\rsakey.py", line 55, in __init__
    self._from_private_key_file(filename, password)
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\paramiko\rsakey.py", line 176, in _from_private_key_file
    self._decode_key(data)
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\paramiko\rsakey.py", line 202, in _decode_key
    ).private_key(default_backend())
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\cryptography\hazmat\primitives\asymmetric\rsa.py", line 317, in private_key
    return backend.load_rsa_private_numbers(self)
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 629, in load_rsa_private_numbers
    return _RSAPrivateKey(self, rsa_cdata, evp_pkey)
  File "C:\Users\gain\miniconda3\envs\linien_dev\lib\site-packages\cryptography\hazmat\backends\openssl\rsa.py", line 361, in __init__
    raise ValueError("Invalid private key", errors)
ValueError: ('Invalid private key', [_OpenSSLErrorWithText(code=67764350, lib=4, func=160, reason=126, reason_text=b'error:040A007E:rsa routines:RSA_check_key_ex:iqmp not inverse of q')])
```

**Comment by bleykauf** [comment]
Fixed by [1508a65](https://github.com/hermitdemschoenenleben/linien/pull/253/commits/1508a652b22288ee69b8affbfc8a2b2834bddfdb).
